structure(list(Gene = c("aac3", "aadA~~~aadA1", "aadA1", "aadA3", 
"ampC", "aph6I", "cas1e", "cas2", "cas3", "cas6e", "ccdB", "chrA", 
"cpsG", "crcB", "dfrA12", "djlC", "dsdA", "elaD", "eno", "espX5~~~yjcF", 
"fdnG", "floR", "frlA", "frlB", "frlC", "frlD", "group_10099", 
"group_1010", "group_10124", "group_1014", "group_1015", "group_10181", 
"group_10211", "group_10218", "group_10282", "group_10284", "group_10295", 
"group_10334", "group_10348", "group_10356", "group_10385", "group_10428", 
"group_10432", "group_1045", "group_1046", "group_10461", "group_10476", 
"group_10500", "group_10554", "group_10557", "group_10594", "group_10598", 
"group_10621", "group_10640", "group_10684", "group_10710", "group_1078", 
"group_10787", "group_10802", "group_10815", "group_10891", "group_1099", 
"group_1112", "group_1164", "group_11686", "group_1169", "group_1171", 
"group_11751", "group_11753", "group_11754", "group_11756", "group_11757", 
"group_1181", "group_1183", "group_11973", "group_11978", "group_11980", 
"group_1215", "group_1234", "group_1237", "group_1248", "group_1249", 
"group_1331", "group_13341", "group_13342", "group_13343", "group_13344", 
"group_13345", "group_13346", "group_13348", "group_13349", "group_1352", 
"group_13814", "group_1401", "group_1408", "group_14135", "group_1425", 
"group_1437", "group_1462", "group_1463", "group_1466", "group_1469", 
"group_1475", "group_148", "group_1509", "group_1511", "group_1514", 
"group_1520", "group_15598", "group_15599", "group_15601", "group_15602", 
"group_1569", "group_1573", "group_1574", "group_1575", "group_1576", 
"group_16249", "group_16250", "group_1626", "group_16327", "group_16328", 
"group_16330", "group_16331", "group_16332", "group_16333", "group_16334", 
"group_16335", "group_16337", "group_16338", "group_16339", "group_16340", 
"group_16341", "group_16353", "group_16354", "group_16355", "group_16356", 
"group_16361", "group_16362", "group_16363", "group_16373", "group_16374", 
"group_16375", "group_16376", "group_16377", "group_16378", "group_16379", 
"group_16380", "group_16381", "group_16382", "group_16383", "group_16384", 
"group_164", "group_16451", "group_16452", "group_16454", "group_16455", 
"group_16456", "group_16457", "group_16458", "group_16459", "group_16460", 
"group_16461", "group_16462", "group_16463", "group_16464", "group_16465", 
"group_16466", "group_16467", "group_16468", "group_16469", "group_16470", 
"group_16471", "group_16516", "group_16519", "group_16530", "group_16531", 
"group_16565", "group_16566", "group_16660", "group_16678", "group_16728", 
"group_16770", "group_16802", "group_16948", "group_16958", "group_16959", 
"group_1710", "group_1719", "group_17272", "group_17282", "group_17291", 
"group_17340", "group_17342", "group_17356", "group_17357", "group_17375", 
"group_17382", "group_17386", "group_17408", "group_17465", "group_17466", 
"group_17477", "group_17478", "group_17479", "group_17480", "group_1758", 
"group_1835", "group_1864", "group_1889", "group_1924", "group_1925", 
"group_1995", "group_1998", "group_2000", "group_2018", "group_203", 
"group_2042", "group_2048", "group_2049", "group_2069", "group_2102", 
"group_2103", "group_2115", "group_2126", "group_2137", "group_2147", 
"group_2181", "group_2212", "group_2267", "group_227", "group_2291", 
"group_2292", "group_2319", "group_2363", "group_2364", "group_2374", 
"group_2394", "group_240", "group_2448", "group_2449", "group_2451", 
"group_2481", "group_2520", "group_2521", "group_2523", "group_2524", 
"group_2569", "group_2592", "group_2595", "group_2655", "group_2664", 
"group_2674", "group_2675", "group_2678", "group_2686", "group_2697", 
"group_2698", "group_2699", "group_2717", "group_2721", "group_2739", 
"group_2756", "group_2776", "group_28", "group_2806", "group_2850", 
"group_2867", "group_2869", "group_2874", "group_2889", "group_2891", 
"group_2929", "group_2942", "group_297", "group_2979", "group_2990", 
"group_3006", "group_3032", "group_3060", "group_3099", "group_3148", 
"group_3183", "group_3197", "group_3242", "group_3245", "group_3256", 
"group_3268", "group_3289", "group_3312", "group_3351", "group_3361", 
"group_340", "group_341", "group_342", "group_3434", "group_3435", 
"group_3467", "group_3471", "group_3493", "group_3504", "group_3528", 
"group_3566", "group_3573", "group_3581", "group_3643", "group_3655", 
"group_3696", "group_3697", "group_3737", "group_380", "group_3824", 
"group_3831", "group_3845", "group_3846", "group_3847", "group_3849", 
"group_3852", "group_3854", "group_3855", "group_3857", "group_3861", 
"group_3892", "group_3907", "group_3921", "group_3933", "group_3938", 
"group_3975", "group_3993", "group_3996", "group_4008", "group_4019", 
"group_4032", "group_4035", "group_4067", "group_4110", "group_4152", 
"group_4248", "group_4268", "group_4271", "group_428", "group_4288", 
"group_4407", "group_4411", "group_4413", "group_4421", "group_4432", 
"group_4434", "group_4438", "group_4455", "group_4458", "group_4459", 
"group_4461", "group_4483", "group_4493", "group_4494", "group_4537", 
"group_4543", "group_4570", "group_4594", "group_4605", "group_4617", 
"group_4618", "group_4619", "group_4628", "group_4637", "group_4642", 
"group_4675", "group_4709", "group_4710", "group_4711", "group_4742", 
"group_4745", "group_4784", "group_4794", "group_4805", "group_4826", 
"group_4831", "group_4838", "group_4847", "group_4863", "group_4866", 
"group_4880", "group_4889", "group_4892", "group_4893", "group_4896", 
"group_4909", "group_4913", "group_4933", "group_4954", "group_497", 
"group_4989", "group_499", "group_5037", "group_504", "group_505", 
"group_5067", "group_5070", "group_5078", "group_508", "group_5080", 
"group_5125", "group_5141", "group_5158", "group_5175", "group_5189", 
"group_5190", "group_5211", "group_5291", "group_5303", "group_5344", 
"group_5365", "group_5373", "group_5374", "group_5392", "group_54", 
"group_5419", "group_5424", "group_5435", "group_5517", "group_5548", 
"group_5551", "group_5667", "group_5678", "group_5680", "group_5683", 
"group_5686", "group_5687", "group_5688", "group_5689", "group_5690", 
"group_5691", "group_5692", "group_5693", "group_5695", "group_5696", 
"group_57", "group_570", "group_5700", "group_5701", "group_5702", 
"group_5703", "group_5706", "group_5707", "group_5708", "group_5709", 
"group_5710", "group_5713", "group_5714", "group_5716", "group_572", 
"group_5720", "group_5723", "group_5724", "group_5725", "group_5735", 
"group_5736", "group_5737", "group_5738", "group_5740", "group_5741", 
"group_5742", "group_5743", "group_5744", "group_5745", "group_5746", 
"group_5747", "group_5748", "group_5749", "group_575", "group_5751", 
"group_5752", "group_5753", "group_5754", "group_5755", "group_5759", 
"group_5760", "group_5762", "group_5766", "group_579", "group_5833", 
"group_5914", "group_5915", "group_5925", "group_5930", "group_5931", 
"group_5932", "group_5933", "group_6053", "group_6151", "group_6152", 
"group_6156", "group_6159", "group_617", "group_6177", "group_6178", 
"group_6180", "group_619", "group_620", "group_6201", "group_6202", 
"group_6203", "group_6204", "group_6205", "group_6241", "group_6298", 
"group_6331", "group_6334", "group_6390", "group_6391", "group_6435", 
"group_6438", "group_6472", "group_6498", "group_6538", "group_6547", 
"group_6660", "group_6674", "group_6691", "group_6717", "group_6729", 
"group_6740", "group_6752", "group_6764", "group_6765", "group_6787", 
"group_6822", "group_6824", "group_6905", "group_6922", "group_6949", 
"group_6987", "group_6990", "group_7002", "group_7031", "group_7054", 
"group_7059", "group_7158", "group_7225", "group_7256", "group_7262", 
"group_7282", "group_7294", "group_732", "group_7373", "group_7374", 
"group_7397", "group_7427", "group_7454", "group_7468", "group_7511", 
"group_7524", "group_7538", "group_7570", "group_758", "group_7601", 
"group_7613", "group_7614", "group_7621", "group_7631", "group_7706", 
"group_7707", "group_7786", "group_7872", "group_7894", "group_792", 
"group_8013", "group_8093", "group_8102", "group_8180", "group_8198", 
"group_8316", "group_8318", "group_8319", "group_8321", "group_8322", 
"group_8323", "group_8324", "group_8326", "group_8328", "group_8333", 
"group_8335", "group_8336", "group_8338", "group_8339", "group_8340", 
"group_8341", "group_8343", "group_8345", "group_8346", "group_8349", 
"group_8353", "group_840", "group_8405", "group_8406", "group_8407", 
"group_8408", "group_8409", "group_8410", "group_8415", "group_8439", 
"group_8449", "group_8462", "group_8466", "group_8471", "group_8473", 
"group_8475", "group_8481", "group_8489", "group_8518", "group_8521", 
"group_8578", "group_8653", "group_8664", "group_8675", "group_870", 
"group_8831", "group_8832", "group_8848", "group_8850", "group_8851", 
"group_8855", "group_8896", "group_8921", "group_8970", "group_8982", 
"group_9010", "group_9038", "group_9054", "group_9133", "group_9142", 
"group_9152", "group_9164", "group_9208", "group_9216", "group_9218", 
"group_9260", "group_9288", "group_9290", "group_9314", "group_9350", 
"group_9354", "group_9378", "group_9386", "group_9388", "group_9401", 
"group_9415", "group_9418", "group_9455", "group_9495", "group_9499", 
"group_9533", "group_9534", "group_9540", "group_9561", "group_9572", 
"group_959", "group_9604", "group_9674", "group_9730", "group_9837", 
"group_9886", "group_9887", "group_990", "group_9900", "group_9981", 
"hpaB", "hpaD", "hpaE", "hpaH", "hpaI", "hpaR", "hpaX", "hyfF", 
"intI1", "iraM", "iucA", "iucB", "iucC", "iutA", "lnuF", "ltrA", 
"mdtM", "meaB", "melB", "merA", "merP", "merR", "merT", "mhpR", 
"mphA", "mqsA", "mqsR", "mtnA", "nanR", "nikB", "ompL", "pemK", 
"pilO2", "pilP", "qac", "repE", "sat", "scpC", "sopA", "ssb", 
"sul1", "sul2", "sul3", "tap", "tetA", "tetB", "tetC", "tetRA", 
"traE", "traF", "traI", "traL", "traN", "traR", "traT", "traU", 
"traX", "trbB", "trbB~~~trbJ", "trbE", "tssI", "wbdA", "wbdC", 
"yaeI", "ygeH", "yggF"), Annotation = c("aminoglycoside 3-N-acetyltransferase;aminoglycoside N-acetyltransferase AAC(3)-IId", 
"AadA family aminoglycoside 3''-O-nucleotidyltransferase;ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA1", 
"ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA1", 
"ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA22;ANT(3'') family aminoglycoside nucleotidyltransferase;ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA3;ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA2", 
"CMY2/MIR/ACT/EC family class C beta-lactamase;beta-lactamase;serine hydrolase", 
"hypothetical protein;APH(6)-I family aminoglycoside O-phosphotransferase;aminoglycoside O-phosphotransferase APH(6)-Id", 
"CRISPR-associated protein Cas1;type I-E CRISPR-associated endonuclease Cas1", 
"type I-E CRISPR-associated endoribonuclease Cas2", "CRISPR-associated helicase Cas3';CRISPR-associated helicase/endonuclease Cas3;CRISPR-associated endonuclease Cas3''", 
"type I-E CRISPR-associated protein Cas6/Cse3/CasE", "plasmid maintenance protein CcdB;cytotoxin;type II toxin-antitoxin system toxin CcdB", 
"chromate efflux transporter", "phosphomannomutase;phosphomannomutase CpsG", 
"fluoride efflux transporter CrcB", "trimethoprim-resistant dihydrofolate reductase DfrA12", 
"J domain-containing protein;co-chaperone DjlC;hypothetical protein", 
"D-serine ammonia-lyase", "deubiquitinase;protease elaD;hypothetical protein", 
"phosphopyruvate hydratase;enolase", "pentapeptide repeat-containing protein;T3SS effector pentapeptide repeat protein EspX5;pentapeptide repeat protein YjcF;hypothetical protein", 
"formate dehydrogenase-N subunit alpha", "chloramphenicol/florfenicol efflux MFS transporter FloR", 
"fructoselysine/psicoselysine transporter", "fructoselysine 6-phosphate deglycase", 
"fructoselysine 3-epimerase", "fructoselysine 6-kinase", "O-antigen ligase family protein", 
"hypothetical protein;pilus protein", "IS66 family transposase;IS66-like element ISEc8 family transposase", 
"hypothetical protein", "antirestriction protein ArdA", "PilN family type IVB pilus formation outer membrane protein", 
"LysR family transcriptional regulator;DNA-binding transcriptional regulator;hypothetical protein", 
"hypothetical protein", "lipoprotein bor;increased serum survival lipoprotein Iss", 
"6-phospho-alpha-glucosidase;inactive 6-phospho-alpha-glucosidase", 
"tail fiber assembly protein;phage tail protein", "replication regulatory protein RepA", 
"hypothetical protein", "type I toxin-antitoxin system toxin Ldr family protein;small toxic polypeptide LdrA/LdrC;small toxic polypeptide LdrB", 
"helix-turn-helix domain-containing protein;transposase;IS200/IS605 family element transposase accessory protein TnpB", 
"hypothetical protein", "hypothetical protein;DNA-binding protein", 
"conjugation system SOS inhibitor PsiB", "hypothetical protein", 
"site-specific integrase;tyrosine-type recombinase/integrase", 
"hypothetical protein;DUF3363 domain-containing protein", "DeoR family transcriptional regulator", 
"phosphatase PAP2 family protein", "hypothetical protein", "DUF2773 domain-containing bactofilin;DUF2773 domain-containing protein", 
"5-carboxymethyl-2-hydroxymuconate Delta-isomerase", "hypothetical protein", 
"hypothetical protein", "TrmB family transcriptional regulator", 
"type I-E CRISPR-associated protein Cas7/Cse4/CasC", "hypothetical protein;type III secretion protein", 
"hypothetical protein", "HEAT repeat domain-containing protein", 
"DUF1440 domain-containing protein", "phage portal protein", 
"hypothetical protein;threonine-rich inner membrane protein GfcA", 
"histidine kinase;EscU/YscU/HrcU family type III secretion system export apparatus switch protein;flagellar biosynthesis protein FlhB;hypothetical protein;flhB HrpN YscU SpaS family protein", 
"hypothetical protein", "hypothetical protein", "hypothetical protein", 
"neurotensin receptor R8", "hypothetical protein", "conjugal transfer protein", 
"radical SAM protein", "AlpA family transcriptional regulator", 
"hypothetical protein", "type-F conjugative transfer system protein TraW;conjugal transfer protein TraW;hypothetical protein", 
"conjugal transfer protein TraA", "hypothetical protein", "relaxase/mobilization nuclease domain-containing protein;relaxase", 
"hypothetical protein", "shufflon protein B;shufflon protein D'", 
"LuxR family transcriptional regulator;invasion protein", "trimethoprim-resistant dihydrofolate reductase DfrA15;trimethoprim-resistant dihydrofolate reductase DfrA7;trimethoprim-resistant dihydrofolate reductase DfrA5;trimethoprim-resistant dihydrofolate reductase DfrA14;trimethoprim-resistant dihydrofolate reductase DfrA1;trimethoprim-resistant dihydrofolate reductase DfrA17", 
"hypothetical protein", "DUF1327 domain-containing protein;YdfR family protein;hypothetical protein", 
"quaternary ammonium compound efflux SMR transporter QacL;EamA family transporter", 
"hypothetical protein", "radical SAM protein", "hypothetical protein", 
"competence CoiA-like family protein", "site-specific DNA-methyltransferase", 
"shufflon system plasmid conjugative transfer pilus tip adhesin PilV", 
"lysis protein;hypothetical protein", "alpha/beta hydrolase", 
"antitermination protein", "hypothetical protein", "DUF3596 domain-containing protein;site-specific integrase", 
"epoxyqueuosine reductase QueH", "HNH endonuclease", "replication initiation protein", 
"bifunctional siderophore receptor/adhesin Iha", "trimethoprim-resistant dihydrofolate reductase DfrA7;trimethoprim-resistant dihydrofolate reductase DfrA5;trimethoprim-resistant dihydrofolate reductase DfrA14;trimethoprim-resistant dihydrofolate reductase DfrA15;trimethoprim-resistant dihydrofolate reductase DfrA1;trimethoprim-resistant dihydrofolate reductase DfrA17", 
"hypothetical protein;DUF262 domain-containing protein", "hypothetical protein", 
"hypothetical protein", "transcription termination factor NusG;conjugal transfer protein TraB", 
"invasion protein", "hypothetical protein", "ArgR family transcriptional regulator", 
"hypothetical protein;IS1380 family transposase;IS1380-like element ISEc9 family transposase", 
"surface exclusion protein;entry exclusion protein", "hypothetical protein", 
"hypothetical protein", "hypothetical protein", "DNA-binding protein", 
"BCCT family transporter", "fimbrial protein;long polar fimbria major subunit LpfA-O113", 
"fimbrial protein", "type IV conjugative transfer system pilin TraA;pilin", 
"pili assembly chaperone", "IS21-like element ISEc12 family transposase", 
"ATP-binding protein", "DUF945 domain-containing protein", "EamA family transporter;hypothetical protein", 
"tetracycline efflux MFS transporter Tet(A)", "hypothetical protein;DUF3363 domain-containing protein", 
"cysteine hydrolase", "sulfonamide-resistant dihydropteroate synthase Sul2", 
"APH(6)-I family aminoglycoside O-phosphotransferase;hypothetical protein;aminoglycoside O-phosphotransferase APH(6)-Id", 
"relaxase;hypothetical protein", "tetracycline resistance transcriptional repressor TetR(A);TetR family transcriptional regulator", 
"transcriptional regulator", "phosphotransferase;aminoglycoside phosphotransferase APH(3');aminoglycoside O-phosphotransferase APH(3'')-Ib", 
"hypothetical protein;replication protein C;replication protein", 
"oxacillin-hydrolyzing class D beta-lactamase OXA-1", "fluoroquinolone-acetylating aminoglycoside 6'-N-acetyltransferase AAC(6')-Ib-cr5", 
"plasmid transfer ATPase TraJ", "conjugal transfer protein", 
"hypothetical protein", "histidine phosphatase family protein", 
"phospholipase D family protein", "conjugal transfer protein", 
"hypothetical protein", "LysR family transcriptional regulator", 
"chloramphenicol/florfenicol efflux MFS transporter FloR", "hypothetical protein", 
"aminoglycoside N-acetyltransferase AAC(3)-IId", "AAA family ATPase", 
"hypothetical protein", "tunicamycin resistance protein;AAA family ATPase", 
"hypothetical protein", "hypothetical protein", "DUF3883 domain-containing protein", 
"hypothetical protein", "DUF3883 domain-containing protein", 
"IS6-like element IS6100 family transposase;hypothetical protein;DDE-type integrase/transposase/recombinase;IS6 family transposase;IS6-like element IS26 family transposase", 
"hypothetical protein", "hypothetical protein;IS91 family transposase;transposase", 
"tetracycline efflux MFS transporter Tet(B)", "TetR family transcriptional regulator", 
"TetR family transcriptional regulator", "ArsR family transcriptional regulator;winged helix-turn-helix transcriptional regulator", 
"ArsR family transcriptional regulator;winged helix-turn-helix transcriptional regulator", 
"antibiotic biosynthesis monooxygenase", "amino acid-binding protein", 
"LysR family transcriptional regulator", "sodium/glutamate symporter", 
"amino acid-binding protein", "sodium/glutamate symporter", "AraC family transcriptional regulator;transposase;helix-turn-helix domain-containing protein", 
"antibiotic biosynthesis monooxygenase", "sodium/glutamate symporter;lipopolysaccharide core heptose(II) kinase RfaY", 
"IS4 family transposase;IS4-like element ISVsa5 family transposase", 
"tetracyline resistance-associated transcriptional repressor TetC;transposase", 
"AraC family transcriptional regulator;transposase;helix-turn-helix domain-containing protein", 
"LysR family transcriptional regulator", "hypothetical protein", 
"aminoglycoside O-phosphotransferase APH(3')-Ia", "GNAT family N-acetyltransferase", 
"type A-1 chloramphenicol O-acetyltransferase", "hypothetical protein", 
"DUF3927 domain-containing protein", "flippase;oligosaccharide flippase family protein", 
"hypothetical protein", "abortive phage infection protein", "DUF4756 family protein", 
"hypothetical protein", "IS4-like element ISVsa5 family transposase;IS4 family transposase", 
"transposase family protein;transposase;DDE-type integrase/transposase/recombinase", 
"ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA1;aminoglycoside nucleotidyltransferase", 
"conjugal transfer protein TraR", "DUF905 domain-containing protein", 
"hypothetical protein;IS6-like element IS26 family transposase", 
"DEAD/DEAH box helicase", "SLATT domain-containing protein", 
"IS5 family transposase;IS5-like element IS903 family transposase;transposase;IS5-like element IS903B family transposase", 
"prepilin-type N-terminal cleavage/methylation domain-containing protein", 
"conjugal transfer protein TraD", "hypothetical protein", "IS1 family transposase;IS1-like element IS1A family transposase;IS1-like element IS1B family transposase", 
"IS1 family transposase;IS1-like element IS1B family transposase;IS1-like element IS1A family transposase", 
"reverse transcriptase;RNA-directed DNA polymerase", "IS6-like element IS26 family transposase;IS6-like element IS1006 family transposase", 
"hypothetical protein", "replication protein", "hypothetical protein", 
"helix-turn-helix transcriptional regulator;XRE family transcriptional regulator", 
"DNA-directed RNA polymerase subunit beta;lipoprotein", "hypothetical protein", 
"molecular chaperone HscC;Hsp70 family protein", "enterotoxin", 
"transporter;MHS family MFS transporter", "type IV secretion system protein TraC;hypothetical protein;conjugal transfer protein TraC", 
"RepB family plasmid replication initiator protein", "transcriptional regulator;serine/threonine protein kinase", 
"methyltransferase domain-containing protein", "glycosyltransferase family 1 protein;glycosyltransferase family 4 protein", 
"hypothetical protein;iraD leader peptide", "plasmid SOS inhibition protein A", 
"hypothetical protein", "DUF1281 domain-containing protein;aerotaxis sensor receptor flavoprotein;DUF4113 domain-containing protein;hypothetical protein", 
"exclusion-determining protein;ethanolamine utilization protein EutE;ethanolamine utilization protein", 
"colicin;colicin-Ia;hypothetical protein;colicin transporter;colicin Ia family protein", 
"peptidoglycan-binding protein;lytic transglycosylase domain-containing protein;transglycosylase SLT domain-containing protein", 
"fimbrial-like protein", "molecular chaperone", "autotransporter outer membrane beta-barrel domain-containing protein;autotransporter-associated beta strand;autotransporter barrel domain-containing lipoprotein;hypothetical protein;transporter", 
"ParB/RepB/Spo0J family partition protein;hypothetical protein;chromosome partitioning protein ParB", 
"DUF2713 family protein;hypothetical protein;DUF2713 domain-containing protein", 
"helix-turn-helix transcriptional regulator;LuxR family transcriptional regulator", 
"YscQ/HrcQ family type III secretion apparatus protein;hypothetical protein", 
"hypothetical protein;DUF1380 domain-containing protein", "hypothetical protein;tyrosine kinase", 
"hypothetical protein", "ParB/RepB/Spo0J family partition protein;hypothetical protein;chromosome partitioning protein ParB", 
"hypothetical protein", "class A extended-spectrum beta-lactamase CTX-M-14;class A extended-spectrum beta-lactamase CTX-M-15", 
"ParA family protein", "hypothetical protein", "lysine 6-monooxygenase;L-lysine N6-monooxygenase", 
"hypothetical protein", "DUF2686 family protein", "transporter;pilus assembly protein;hypothetical protein", 
"Rpn family recombination-promoting nuclease/putative transposase", 
"CesD/SycD/LcrH family type III secretion system chaperone;tetratricopeptide repeat protein", 
"EscJ/YscJ/HrcJ family type III secretion inner membrane ring protein;hypothetical protein", 
"hypothetical protein;DotA/TraY family protein", "positive regulator for repZ translation;hypothetical protein", 
"peptidase;translesion error-prone DNA polymerase V autoproteolytic subunit", 
"DUF4942 domain-containing protein", "type-F conjugative transfer system secretin TraK", 
"relaxase;hypothetical protein", "hypothetical protein", "conjugal transfer protein TraC", 
"hypothetical protein", "class A extended-spectrum beta-lactamase CTX-M-14;class A extended-spectrum beta-lactamase CTX-M-15", 
"colicin;hypothetical protein;colicin transporter", "conjugal transfer protein TraG;conjugal transfer mating pair stabilization protein TraG", 
"replication regulatory protein RepA;replication protein RepA;hypothetical protein;replication protein", 
"fimbrial chaperone", "fimbrial biogenesis outer membrane usher protein;fimbria/pilus outer membrane usher protein;hypothetical protein", 
"hypothetical protein;pili assembly chaperone", "hypothetical protein", 
"LysR family transcriptional regulator;hypothetical protein", 
"DUF4049 domain-containing protein;hypothetical protein", "protein tyrosine phosphatase", 
"acyl-CoA dehydrogenase", "IS30-like element IS30H family transposase;IS30-like element IS30 family transposase;IS30 family transposase", 
"hypothetical protein;fimbrial protein", "hypothetical protein", 
"phage portal protein", "molybdopterin-guanine dinucleotide biosynthesis protein MobC", 
"DUF968 domain-containing protein;pdcB", "nikA protein", "recombinase family protein;adenine-specific DNA-methyltransferase;510-methylenetetrahydrofolate reductase;metal-dependent hydrolase", 
"DUF957 domain-containing protein", "fimbrial protein;fimbrial subunit ElfA", 
"DUF945 domain-containing protein;DUF932 domain-containing protein", 
"hypothetical protein;PTS transporter subunit EIIA;HTH domain-containing protein;transcriptional regulator", 
"ISAs1 family transposase;ISAs1-like element ISEc5 family transposase;ISAs1-like element ISEc1 family transposase;transposase", 
"hypothetical protein", "hypothetical protein", "conjugation system SOS inhibitor PsiB", 
"xanthine dehydrogenase family protein molybdopterin-binding subunit;oxidoreductase;molybdopterin-dependent oxidoreductase;xanthine dehydrogenase family protein subunit M", 
"DUF905 domain-containing protein", "DUF987 domain-containing protein;DUF987 family protein", 
"hypothetical protein", "restriction endonuclease subunit S", 
"type-F conjugative transfer system pilin assembly protein TrbC", 
"RepA leader peptide Tap", "type I toxin-antitoxin system Hok family toxin", 
"hypothetical protein", "single-stranded DNA-binding protein;hypothetical protein", 
"hypothetical protein", "hypothetical protein", "DUF1472 domain-containing protein", 
"hypothetical protein", "type VI secretion system tip protein VgrG;hypothetical protein", 
"DUF1380 domain-containing protein", "DUF1380 domain-containing protein", 
"S-methylmethionine permease", "YfcC family protein", "conjugal transfer protein TraH", 
"hypothetical protein", "chromosome partitioning protein ParB;ParB/RepB/Spo0J family partition protein;hypothetical protein", 
"ATP-binding protein", "fertility inhibition protein FinO;conjugal transfer protein", 
"DUF1472 domain-containing protein;YubH family protein", "antirestriction protein", 
"conjugal transfer protein TrbA", "hypothetical protein", "complement resistance protein TraT;hypothetical protein", 
"DUF4238 domain-containing protein", "DUF4132 domain-containing protein;WGR and DUF4132 domain-containing protein;molybdate metabolism regulator", 
"IS66 family insertion sequence hypothetical protein;IS66 family insertion sequence element accessory protein TnpB;transposase", 
"AAA family ATPase", "GNAT family N-acetyltransferase;hypothetical protein", 
"resolvase;NTP-binding protein", "conjugal transfer protein TraE", 
"Tn3 family transposase;Tn3-like element TnAs3 family transposase;DUF4158 domain-containing protein;Tn3-like element TnAs1 family transposase;hypothetical protein;transposase", 
"hypothetical protein", "hypothetical protein", "recombinase family protein;helix-turn-helix domain-containing protein;hypothetical protein", 
"hypothetical protein", "hypothetical protein", "hypothetical protein", 
"replication protein RepA4;replication protein;hypothetical protein", 
"capsule assembly Wzi family protein", "hypothetical protein;RHS repeat protein;RHS repeat family protein;type IV secretion protein Rhs;RHS element protein;RHS repeat-associated core domain-containing protein", 
"hypothetical protein", "IS1 family transposase;IS1-like element IS1A family transposase;hypothetical protein", 
"resolvase", "DUF1281 domain-containing protein", "recombinase family protein;helix-turn-helix domain-containing protein", 
"Tn3 family transposase;hypothetical protein;Tn3-like element TnAs1 family transposase;transposase", 
"GTPase family protein", "replication C family protein;replication protein C;replication protein", 
"polysaccharide export protein", "p-aminobenzoyl-glutamate hydrolase subunit A", 
"antitoxin of toxin-antitoxin stability system", "4-hydroxyphenylacetate degradation bifunctional isomerase/decarboxylase", 
"hypothetical protein;DUF1472 domain-containing protein", "DUF2787 domain-containing protein", 
"hypothetical protein", "molybdopterin-guanine dinucleotide biosynthesis protein MobC", 
"PstS family phosphate ABC transporter substrate-binding protein;phosphate ABC transporter substrate-binding protein;hypothetical protein", 
"RusA family crossover junction endodeoxyribonuclease", "hypothetical protein", 
"transposase;Tn3-like element Tn3 family transposase;Tn3 family transposase;DUF4158 domain-containing protein", 
"proQ/FINO family protein", "abortive infection protein", "hypothetical protein;cobalamin biosynthesis protein CobW", 
"AbrB/MazE/SpoVT family DNA-binding domain-containing protein", 
"hypothetical protein", "colicin transporter;colicin 1B immunity protein", 
"esterase-like activity of phytase family protein;hypothetical protein", 
"hypothetical protein", "polysaccharide biosynthesis tyrosine autokinase", 
"type II toxin-antitoxin system VapC family toxin;PIN domain-containing protein", 
"hypothetical protein", "DNA repair protein RadC", "S-methyl-5-thioribose kinase", 
"RusA family crossover junction endodeoxyribonuclease;hypothetical protein", 
"hypothetical protein", "AbrB/MazE/SpoVT family DNA-binding domain-containing protein", 
"hypothetical protein", "DNA helicase UvrD", "relaxosome protein TraM", 
"site-specific integrase;tyrosine-type recombinase/integrase", 
"DUF977 family protein", "AAA family ATPase;ATP-dependent endonuclease", 
"mannose-1-phosphate guanylyltransferase/mannose-6-phosphate isomerase", 
"ABC transporter permease;O99 family O-antigen ABC transporter permease subunit Wzm;O9 family O-antigen ABC transporter permease subunit Wzm", 
"ABC transporter ATP-binding protein;O9 family O-antigen ABC transporter ATP-binding protein Wzt", 
"DNA repair protein;hypothetical protein;DUF4113 domain-containing protein;translesion error-prone DNA polymerase V subunit UmuC;Y-family DNA polymerase", 
"GGDEF domain-containing protein;diguanylate cyclase", "relaxase NikB;relaxase/mobilization nuclease domain-containing protein;IncI1-type relaxase NikB", 
"IS110 family transposase", "IS3 family transposase;hypothetical protein", 
"conjugal transfer protein TrbA;IncI1-type conjugal transfer protein TrbA;hypothetical protein", 
"conjugal transfer protein TrbC;TraM recognition domain-containing protein", 
"DUF262 domain-containing protein", "IS66 family insertion sequence element accessory protein TnpB;IS66 family insertion sequence hypothetical protein", 
"Rpn family recombination-promoting nuclease/putative transposase", 
"hypothetical protein", "hypothetical protein", "ethanolamine utilization protein EutE;exclusion-determining protein;ethanolamine utilization protein", 
"plasmid-partitioning protein;ParB/RepB/Spo0J family plasmid partition protein", 
"hypothetical protein", "Tn3 family transposase;transposase;Tn3-like element TnAs3 family transposase", 
"conjugative transfer relaxase/helicase TraI;hypothetical protein;DNA helicase;traI domain protein;AAA family ATPase", 
"IS5-like element ISKpn26 family transposase;IS5-like element IS5 family transposase;IS5/IS1182 family transposase", 
"IS4-like element IS4 family transposase;IS4 family transposase;transposase", 
"IS21 family transposase;transposase", "GNAT family N-acetyltransferase;hypothetical protein", 
"DNA cytosine methyltransferase", "glutathione S-transferase;type VII secretion-associated protein", 
"arginine deiminase", "conjugal transfer protein", "lipopolysaccharide core heptose(II)-phosphate phosphatase;histidine phosphatase family protein", 
"phage major capsid protein", "transposase;IS66 family insertion sequence hypothetical protein", 
"PilI type IV pilus biogenesis protein;pilus assembly protein", 
"LysR family transcriptional regulator", "DUF2254 domain-containing protein", 
"ISL3-like element ISKox3 family transposase;ISL3 family transposase", 
"IS5/IS1182 family transposase;IS5 family transposase;IS5-like element IS903 family transposase;transposase;IS5-like element IS903B family transposase", 
"single-stranded DNA-binding protein", "protease;omptin family outer membrane protease", 
"antimicrobial resistance protein Mig-14", "NAD-dependent epimerase/dehydratase family protein", 
"Hok/Gef family protein", "DUF1391 domain-containing protein", 
"hypothetical protein;GTPase", "conjugal transfer protein TraF", 
"hypothetical protein", "hypothetical protein", "type IV conjugative transfer system protein TraV;type IV conjugative transfer system lipoprotein TraV", 
"IS3 family transposase;transposase;IS3-like element IS600 family transposase", 
"transcriptional regulator", "LuxR family transcriptional regulator", 
"MFS transporter", "MFS transporter", "putative C-S lyase", "3-(3-hydroxy-phenyl)propionate transporter", 
"acetaldehyde dehydrogenase (acetylating)", "type I toxin-antitoxin system Hok family toxin", 
"antitoxin PemI", "cysteine hydrolase", "cupin fold metalloprotein WbuC family", 
"ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA5", 
"ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA5", 
"quaternary ammonium compound efflux SMR transporter QacE delta 1", 
"quaternary ammonium compound efflux SMR transporter QacE delta 1", 
"hypothetical protein", "trimethoprim-resistant dihydrofolate reductase DfrA12", 
"DUF1010 domain-containing protein", "DUF1010 domain-containing protein", 
"hypothetical protein", "hypothetical protein", "fimbrial biogenesis outer membrane usher protein", 
"PdcA protein", "IS6-like element IS6100 family transposase", 
"type VII secretion-associated protein", "hypothetical protein", 
"TetR/AcrR family transcriptional regulator", "TetR/AcrR family transcriptional regulator", 
"MFS transporter", "Mph(A) family macrolide 2'-phosphotransferase", 
"hypothetical protein", "hypothetical protein", "ABC transporter ATP-binding protein", 
"ABC transporter permease", "DUF2318 domain-containing protein", 
"toxin ArtA;protein ArtA", "protein disulfide oxidoreductase", 
"conjugal transfer protein TrbA", "DsbC family protein", "conjugal transfer protein TrbC", 
"conjugal transfer protein TraV", "ATP-binding protein", "TraS protein", 
"conjugal transfer protein TraP", "conjugal transfer protein TraN", 
"conjugal transfer protein TraM", "conjugal transfer protein", 
"plasmid transfer ATPase TraJ", "conjugal transfer protein", 
"hypothetical protein", "conjugal transfer protein TraF", "shufflon protein C'", 
"prepilin peptidase", "lytic transglycosylase domain-containing protein", 
"phage integrase family protein", "pilus assembly protein PilR", 
"ATP-binding protein", "pilus assembly protein PilP", "pili assembly chaperone", 
"hypothetical protein", "class A broad-spectrum beta-lactamase TEM-1", 
"class A broad-spectrum beta-lactamase TEM-1", "korC", "hypothetical protein", 
"hypothetical protein;IS1380 family transposase;IS1380-like element ISEc9 family transposase", 
"hypothetical protein", "type II toxin-antitoxin system death-on-curing family toxin", 
"type II toxin-antitoxin system Phd/YefM family antitoxin", "recombinase", 
"LuxR family transcriptional regulator", "lipocalin family protein", 
"lipocalin family protein", "beta-lactamase", "hypothetical protein", 
"IS256 family transposase", "IS256 family transposase", "hypothetical protein", 
"chloramphenicol efflux MFS transporter CmlA1", "hypothetical protein", 
"broad-spectrum mercury transporter MerE", "mercury resistance co-regulator MerD", 
"organomercurial transporter MerC", "transposase;DUF3330 domain-containing protein;hypothetical protein", 
"transposase;DUF3330 domain-containing protein;EAL domain-containing protein;hypothetical protein", 
"SDR family oxidoreductase", "SDR family oxidoreductase", "hypothetical protein", 
"hypothetical protein", "sulfonamide-resistant dihydropteroate synthase Sul3", 
"hypothetical protein", "type I deoxyribonuclease HsdR", "hypothetical protein", 
"DUF927 domain-containing protein", "lipopolysaccharide core heptose(II)-phosphate phosphatase", 
"lipopolysaccharide core heptose(II)-phosphate phosphatase", 
"MFS transporter", "toxin-antitoxin system antitoxin component AbrB family protein", 
"ornithine carbamoyltransferase", "antirestriction protein", 
"hypothetical protein", "hypothetical protein", "helix-turn-helix domain-containing protein", 
"anti-adapter protein IraM", "N-acetyltransferase", "type I toxin-antitoxin system Ibs family toxin", 
"DNA cytosine methyltransferase", "aldolase", "amidohydrolase;p-aminobenzoyl-glutamate hydrolase subunit B", 
"hypothetical protein", "hypothetical protein", "hypothetical protein", 
"hypothetical protein", "homocysteine S-methyltransferase", "SpnT protein", 
"N-acetylneuraminate lyase", "helix-turn-helix transcriptional regulator;hypothetical protein", 
"IS3 family transposase", "carbamate kinase", "sce7725 family protein;hypothetical protein", 
"type II toxin-antitoxin system HigB family toxin;mRNA interferase HigB", 
"N-acetylneuraminic acid channel protein", "glycosyltransferase family 2 protein", 
"4-hydroxyphenylacetate catabolism regulatory protein HpaA", 
"IS200/IS605 family transposase", "fimbrial family protein;hypothetical protein", 
"DNA methylase", "N-acetylmannosamine kinase", "MFS transporter", 
"4-hydroxyphenylacetate 3-monooxygenase reductase subunit", "DUF977 family protein", 
"Rpn family recombination-promoting nuclease/putative transposase", 
"iron/manganese ABC transporter permease subunit SitD", "alpha/beta hydrolase", 
"DUF1471 domain-containing protein", "conjugal transfer relaxosome protein TraY", 
"alcohol dehydrogenase", "RNA-directed DNA polymerase", "hypothetical protein", 
"DUF4158 domain-containing protein;Tn3-like element Tn5403 family transposase", 
"type I toxin-antitoxin system Ibs family toxin", "hypothetical protein", 
"hypothetical protein", "glycosyltransferase family 2 protein", 
"alpha/beta hydrolase", "LysR family transcriptional regulator", 
"post-segregation killing protein PndC", "hypothetical protein", 
"plasmid SOS inhibition protein A", "type I toxin-antitoxin system toxin Ldr family protein", 
"pilus assembly protein PilS;pilus assembly protein PilX", "TetR/AcrR family transcriptional regulator;TetR family transcriptional regulator", 
"transposase;transposase family protein;IS3 family transposase", 
"pilus assembly protein PilV", "hypothetical protein", "hypothetical protein", 
"hypothetical protein;biofilm development YmgB/AriR family protein", 
"cupin fold metalloprotein WbuC family", "hypothetical protein;sulfonamide-resistant dihydropteroate synthase Sul1", 
"hypothetical protein;sulfonamide-resistant dihydropteroate synthase Sul1", 
"PadR family transcriptional regulator;helix-turn-helix transcriptional regulator", 
"PadR family transcriptional regulator;helix-turn-helix transcriptional regulator", 
"MFS transporter", "TlpA family protein disulfide reductase", 
"ABC transporter permease", "scsC protein", "hypothetical protein", 
"Hok/Gef family protein", "conjugal transfer protein;IncI1-type conjugal transfer protein TraW", 
"conjugal transfer protein TraO", "DNA primase;hypothetical protein;mobilization protein", 
"conjugal transfer protein TraE", "shufflon protein C", "conjugal transfer protein TraD", 
"ash family protein;hypothetical protein", "recombinase family protein;hypothetical protein", 
"DUF3800 domain-containing protein;hypothetical protein", "XRE family transcriptional regulator;helix-turn-helix transcriptional regulator", 
"flagellin FliC;FliC/FljB family flagellin", "hypothetical protein", 
"recombinase", "molecular chaperone GroEL", "hypothetical protein;DUF4165 domain-containing protein", 
"quaternary ammonium compound efflux SMR transporter SugE;quaternary ammonium compound-resistance protein SugE", 
"quaternary ammonium compound efflux SMR transporter SugE;quaternary ammonium compound-resistance protein SugE", 
"APH(3'') family aminoglycoside O-phosphotransferase;aminoglycoside phosphotransferase APH(3');aminoglycoside O-phosphotransferase APH(3'')-Ib", 
"shufflon protein D'", "GNAT family N-acetyltransferase", "alpha/beta hydrolase", 
"transcriptional regulator PhoB", "hypothetical protein", "hypothetical protein", 
"ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA3;ANT(3'')-Ia family aminoglycoside nucleotidyltransferase AadA2", 
"transposase;transposase family protein;DDE-type integrase/transposase/recombinase", 
"hypothetical protein;DUF4165 domain-containing protein", "hypothetical protein", 
"Alw26I/Eco31I/Esp3I family type II restriction adenine-specific DNA-methyltransferase", 
"YjhT family mutarotase", "phage tail protein;Ig domain-containing protein", 
"conjugal transfer protein TraJ;conjugal transfer transcriptional regulator TraJ", 
"alcohol dehydrogenase", "glutathione S-transferase", "chromate efflux transporter", 
"conjugal transfer protein TraQ", "EamA family transporter", 
"phospholipase D family protein", "integrase", "hypothetical protein", 
"hypothetical protein", "hypothetical protein", "DNA methylase", 
"DUF3927 domain-containing protein", "type 1 fimbria chaperone FimC", 
"Alw26I/Eco31I/Esp3I family type II restriction endonuclease", 
"ferric iron reductase;IucA/IucC family siderophore biosynthesis protein", 
"type VI secretion system tube protein Hcp;Hcp family type VI secretion system effector", 
"excisionase family protein;DNA-binding protein", "sel1 repeat family protein", 
"hypothetical protein", "nucleotidyltransferase", "hypothetical protein", 
"hypothetical protein", "hypothetical protein", "histidine phosphatase family protein;CPBP family intramembrane metalloprotease", 
"hypothetical protein", "protein sok", "integrase;class 1 integron integrase IntI1", 
"IS91-like element ISVsa3 family transposase;IS91 family transposase", 
"hypothetical protein", "hemolysin activation protein", "Tn3-like element Tn3 family transposase;Tn3 family transposase;DUF4158 domain-containing protein", 
"conjugal transfer protein TraA", "galactonate dehydratase", 
"transcriptional regulator", "DUF3560 domain-containing protein;hydrolase", 
"macrolide transporter;MFS transporter", "IS5-like element IS5 family transposase", 
"EAL domain-containing protein", "EAL domain-containing protein", 
"hypothetical protein", "hypothetical protein", "lipopolysaccharide core heptose(II) kinase RfaY", 
"EscR/YscR/HrcR family type III secretion system export apparatus protein", 
"hypothetical protein", "molecular chaperone", "DNA resolvase", 
"DUF1266 domain-containing protein", "HK97 family phage prohead protease", 
"transcriptional regulator", "type 1 fimbrial protein", "ShET2/EspL2 family type III secretion system effector toxin;hypothetical protein", 
"hypothetical protein", "4-hydroxyphenylacetate 3-monooxygenase oxygenase component", 
"34-dihydroxyphenylacetate 23-dioxygenase", "5-carboxymethyl-2-hydroxymuconate semialdehyde dehydrogenase", 
"2-oxo-hepta-3-ene-17-dioic acid hydratase", "4-hydroxy-2-oxoheptanedioate aldolase", 
"homoprotocatechuate degradation operon regulator HpaR", "4-hydroxyphenylacetate permease", 
"hydrogenase;hypothetical protein;hydrogenase 4 subunit F", "class 1 integron integrase IntI1", 
"anti-adapter protein IraM", "IucA/IucC family siderophore biosynthesis protein;aerobactin synthase IucA", 
"N(6)-hydroxylysine O-acetyltransferase", "IucA/IucC family siderophore biosynthesis protein;hypothetical protein;aerobactin synthase IucC", 
"TonB-dependent receptor;ferric aerobactin receptor IutA", "lincosamide nucleotidyltransferase Lnu(F)", 
"group II intron reverse transcriptase/maturase", "multidrug efflux MFS transporter MdtM", 
"methylmalonyl Co-A mutase-associated GTPase MeaB", "melibiose:sodium transporter MelB", 
"mercury(II) reductase;hypothetical protein", "mercury resistance system periplasmic binding protein MerP", 
"MerR family DNA-binding protein;Hg(II)-responsive transcriptional regulator", 
"mercuric ion transporter MerT", "DNA-binding transcriptional activator MhpR", 
"Mph(A) family macrolide 2'-phosphotransferase", "type II toxin-antitoxin system antitoxin MqsA", 
"type II toxin-antitoxin system MqsR family toxin;type II toxin-antitoxin system toxin MqsR", 
"S-methyl-5-thioribose-1-phosphate isomerase", "transcriptional regulator NanR", 
"relaxase NikB;IncI1-type relaxase NikB", "porin OmpL", "type II toxin-antitoxin system PemK/MazF family toxin;mRNA interferase PemK;type II toxin-antitoxin system toxin endoribonuclease PemK", 
"type 4b pilus protein PilO2;pilus assembly protein PilO", "type IV pilus biogenesis protein PilP", 
"quaternary ammonium compound efflux SMR transporter QacL", "RepB family plasmid replication initiator protein;replication initiation protein RepE", 
"serine protease autotransporter toxin Sat", "propionyl-CoA:succinate CoA transferase", 
"plasmid-partitioning protein SopA", "single-stranded DNA-binding protein", 
"sulfonamide-resistant dihydropteroate synthase Sul1", "sulfonamide-resistant dihydropteroate synthase Sul2", 
"sulfonamide-resistant dihydropteroate synthase Sul3", "RepA leader peptide Tap", 
"tetracycline efflux MFS transporter Tet(A)", "tetracycline efflux MFS transporter Tet(B)", 
"transposase;tetracyline resistance-associated transcriptional repressor TetC", 
"tetracycline resistance transcriptional repressor TetR(A);TetR family transcriptional regulator", 
"type IV conjugative transfer system protein TraE", "type-F conjugative transfer system pilin assembly protein TraF", 
"conjugative transfer relaxase/helicase TraI;conjugal transfer nickase/helicase TraI;protein traI;traI domain protein;DNA helicase;conjugative relaxase;AAA family ATPase;hypothetical protein", 
"type IV conjugative transfer system protein TraL", "type-F conjugative transfer system mating-pair stabilization protein TraN;conjugal transfer protein TraN", 
"IncI1-type conjugal transfer protein TraR;conjugal transfer protein TraR", 
"IncI1-type conjugal transfer protein TraT;conjugal transfer protein TraT", 
"conjugal transfer protein TraU;conjugal transfer pilus assembly protein TraU;conjugal transfer protein", 
"IncI1-type conjugal transfer protein TraX;conjugal transfer protein TraX", 
"IncI1-type conjugal transfer protein TrbB;DsbC family protein", 
"type-F conjugative transfer system pilin assembly thiol-disulfide isomerase TrbB;P-type conjugative transfer protein TrbJ", 
"conjugal transfer protein TrbE", "type VI secretion system tip protein VgrG;type VI secretion protein VgrG;hypothetical protein;type VI secretion protein", 
"polymannosyl GlcNAc-diphospho-ditransoctacis-undecaprenol 23-alpha-mannosylpolymerase WbdA", 
"N-acetyl-alpha-D-glucosaminyl-diphospho-ditransoctacis-undecaprenol 3-alpha-mannosyltransferase WbdC;glycosyltransferase", 
"phosphodiesterase YaeI", "HilA family transcriptional regulator YgeH;transcriptional regulator;hypothetical protein", 
"class II fructose-bisphosphatase"), amox_clauv_acid = c(NA, 
NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, 7L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 13L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 13L, 7L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 6L, 
5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, 6L, 6L, NA, 6L, 6L, 6L, 
6L, 6L, NA, NA, NA, 6L, 6L, NA, NA, NA, NA, NA, NA, 10L, 9L, 
NA, NA, 11L, NA, NA, NA, NA, 6L, 7L, 7L, 7L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 6L, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 4L, NA, NA, 7L, 7L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 10L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA), amp = c(6L, NA, NA, NA, 7L, 6L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 6L, 5L, 5L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 5L, 
5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, 6L, NA, NA, 
NA, NA, NA, 8L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, 5L, NA, NA, NA, 13L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 8L, 6L, NA, NA, 7L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 3L, 4L, NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, 6L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 11L, 
NA, NA, NA, NA, NA, NA, 4L, NA, NA, 5L, 5L, 1L, 6L, NA, NA, NA, 
5L, NA, 13L, 7L, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 5L, NA, NA, 5L, NA, 
NA, NA, NA, 6L, NA, NA, NA, 5L, 4L, NA, NA, 3L, NA, NA, NA, NA, 
NA, NA, 5L, 7L, 2L, 6L, 5L, NA, NA, NA, 7L, NA, NA, NA, NA, NA, 
NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 
1L, 5L, NA, NA, NA, 5L, 4L, NA, 5L, NA, NA, NA, NA, NA, NA, 5L, 
NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 5L, NA, 4L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, NA, NA, NA, NA, 
NA, 7L, NA, 5L, 5L, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 4L, 1L, NA, NA, NA, NA, NA, NA, NA, NA, 6L, 
12L, NA, 11L, 10L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
7L, NA, NA, 7L, NA, 7L, 7L, 7L, NA, NA, NA, NA, NA, NA, 4L, NA, 
4L, 6L, 6L, 6L, 5L, 6L, 6L, 6L, 6L, 6L, 5L, 5L, NA, 6L, 6L, NA, 
5L, 5L, 5L, 5L, 5L, 10L, 9L, NA, 5L, 11L, NA, NA, NA, NA, NA, 
7L, 7L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 10L, 9L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, 6L, 6L, NA, 
6L, NA, NA, NA, NA, NA, NA, 12L, NA, NA, 6L, NA, 7L, NA, NA, 
NA, NA, 4L, 6L, 5L, 5L, NA, NA, 5L, 5L, 2L, NA, 6L, NA, 4L, 4L, 
3L, NA, 7L, 7L, 6L, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 
NA, NA, 3L, NA, NA, 6L, 5L, NA, 5L, 6L, 5L, NA, NA, 3L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, 5L, 10L, 5L, 
NA, NA, 3L, 5L, NA, 7L, NA, NA, NA, NA, NA, NA, 8L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
10L, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 5L, 5L, 5L, 5L, 
NA, 7L, NA, NA, NA, NA, NA, NA, 10L, 5L, 6L, NA, NA, NA, NA, 
NA, 5L, NA, 8L, NA, NA, NA, NA, NA, NA, 3L, 3L, NA, 3L, NA, 5L, 
6L, NA, 5L, 4L, NA, NA, NA, NA, NA, NA, NA, NA), cefalexin.comb = c(NA, 
NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 13L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 6L, 4L, NA, NA, NA, NA, 13L, 7L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 12L, NA, 11L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 11L, NA, NA, NA, NA, NA, 7L, 7L, 7L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 6L, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, 
12L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, 7L, 7L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 10L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 11L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA), cefazolin = c(NA, 4L, 4L, NA, 7L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 1L, NA, 6L, 5L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 7L, 5L, 5L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 3L, 6L, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 6L, NA, NA, NA, 3L, 7L, NA, NA, 1L, 6L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, 5L, NA, 
NA, NA, 13L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 2L, 
2L, 2L, 2L, 2L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 1L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 2L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, 8L, NA, NA, NA, 7L, NA, 
NA, NA, 7L, 6L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, 2L, 
5L, 3L, 11L, 3L, 3L, NA, NA, NA, NA, 4L, NA, NA, 5L, 5L, NA, 
6L, NA, NA, 5L, 5L, NA, 13L, 7L, NA, NA, NA, NA, 5L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 2L, NA, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 2L, NA, NA, NA, 7L, NA, NA, NA, NA, 6L, NA, 5L, 
NA, NA, 5L, NA, NA, NA, 8L, 6L, NA, NA, NA, 5L, NA, NA, NA, NA, 
4L, NA, NA, NA, NA, NA, 5L, 7L, NA, 6L, 5L, NA, NA, 1L, NA, NA, 
NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
6L, 2L, NA, NA, NA, 5L, 4L, NA, NA, 5L, 4L, NA, 5L, NA, NA, NA, 
NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 
4L, NA, NA, 3L, 3L, NA, NA, 1L, NA, NA, 1L, NA, NA, 11L, NA, 
NA, NA, NA, NA, NA, NA, NA, 5L, 5L, 5L, NA, 5L, NA, NA, NA, 6L, 
NA, NA, NA, NA, 3L, NA, 2L, 1L, NA, 4L, NA, 9L, NA, NA, NA, NA, 
NA, NA, NA, NA, 12L, NA, 11L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 4L, NA, 4L, 6L, 6L, 6L, 5L, 6L, 6L, 6L, 6L, 6L, 5L, 5L, 
4L, 6L, 6L, 2L, 5L, 5L, 5L, 5L, 5L, 10L, 9L, NA, 5L, 11L, NA, 
NA, NA, 2L, 6L, 7L, 7L, 7L, NA, 7L, 6L, 5L, NA, 4L, NA, NA, NA, 
10L, NA, 6L, 3L, 6L, 4L, 3L, NA, NA, NA, NA, 4L, 1L, NA, NA, 
NA, 3L, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 3L, NA, NA, NA, NA, 
6L, 6L, 6L, NA, 6L, NA, NA, 4L, NA, NA, NA, 12L, NA, NA, NA, 
NA, NA, NA, NA, NA, 4L, 4L, 6L, 5L, 5L, 1L, 4L, 5L, 5L, 2L, NA, 
6L, NA, 4L, 4L, 3L, 4L, 7L, 7L, NA, 4L, NA, NA, NA, NA, 7L, NA, 
NA, 10L, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 5L, 6L, 5L, 
NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, 
NA, NA, 10L, NA, 4L, NA, 3L, 5L, NA, NA, NA, 6L, NA, NA, NA, 
1L, 8L, NA, NA, NA, NA, NA, NA, 5L, NA, 3L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, 10L, 5L, 6L, 
NA, NA, NA, NA, NA, 5L, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 5L, 6L, NA, 5L, 4L, 8L, NA, NA, NA, 7L, NA, NA, NA
), cefovecin = c(NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 6L, 5L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
5L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, 
NA, NA, 3L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, 5L, NA, NA, NA, 13L, 
NA, NA, NA, NA, NA, NA, 2L, NA, NA, 4L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 6L, 6L, NA, NA, NA, NA, NA, NA, 
5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 8L, NA, NA, NA, NA, NA, NA, NA, 7L, 6L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 11L, 
NA, NA, NA, NA, NA, NA, 4L, NA, NA, 5L, 5L, NA, 6L, NA, 8L, NA, 
5L, 3L, 13L, 7L, NA, NA, NA, 3L, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 7L, NA, NA, NA, NA, 6L, 5L, 5L, NA, NA, 5L, NA, 
NA, NA, 8L, 6L, NA, NA, NA, 5L, NA, NA, NA, NA, 4L, NA, NA, NA, 
NA, NA, 5L, NA, NA, 6L, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, 
NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 
NA, 5L, 4L, NA, NA, 5L, NA, NA, 5L, NA, 2L, NA, NA, NA, NA, 5L, 
2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, 3L, 
3L, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 5L, 5L, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 3L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 12L, 
7L, 11L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, 
6L, 6L, 6L, 5L, 6L, 6L, 6L, 6L, 6L, 5L, 5L, 4L, 6L, 6L, NA, 5L, 
5L, 5L, 5L, 5L, NA, NA, NA, 5L, 11L, NA, NA, NA, NA, 6L, 7L, 
7L, 7L, NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, 6L, 6L, 6L, NA, 6L, NA, 
NA, 4L, NA, NA, NA, 12L, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 
NA, 6L, 5L, 5L, NA, 4L, 5L, 5L, NA, NA, 6L, NA, NA, NA, NA, NA, 
7L, 7L, NA, 4L, NA, NA, NA, NA, NA, NA, NA, 10L, NA, NA, NA, 
NA, NA, NA, NA, NA, 5L, 7L, 5L, 6L, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, NA, NA, NA, 4L, 
NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 8L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 3L, NA, 10L, 5L, 6L, NA, NA, NA, NA, 2L, 5L, 
NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, 5L, 6L, NA, 
5L, NA, 8L, NA, NA, NA, NA, NA, NA, NA), cefpodoxime = c(NA, 
4L, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 1L, NA, NA, 3L, 3L, 3L, 3L, NA, NA, 2L, 6L, 5L, 5L, NA, 
NA, NA, NA, NA, NA, NA, NA, 1L, 7L, NA, 5L, 5L, NA, NA, 1L, NA, 
NA, 1L, NA, NA, NA, NA, NA, 1L, 3L, 6L, NA, 5L, NA, 1L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 3L, 7L, NA, 1L, 
NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, 
NA, NA, NA, NA, NA, 5L, 1L, NA, NA, 13L, NA, NA, NA, NA, NA, 
NA, 2L, 2L, NA, 4L, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 6L, 6L, 2L, 2L, 2L, 2L, 2L, 2L, 5L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 2L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 
NA, 8L, NA, NA, 3L, NA, NA, NA, NA, 7L, 6L, 2L, 1L, NA, NA, NA, 
NA, NA, 1L, NA, 2L, NA, 2L, 5L, 3L, 11L, 3L, 3L, NA, NA, NA, 
1L, 4L, 1L, 1L, 5L, 5L, NA, 6L, 4L, 8L, 5L, 5L, NA, 13L, 7L, 
NA, NA, 1L, 3L, 5L, NA, NA, NA, NA, NA, NA, NA, 1L, NA, 2L, NA, 
5L, NA, NA, NA, NA, NA, NA, 2L, NA, NA, 1L, 2L, NA, 1L, NA, 7L, 
NA, NA, NA, NA, NA, 5L, 5L, 1L, NA, 5L, NA, NA, NA, 8L, 6L, NA, 
NA, NA, 5L, 4L, NA, NA, NA, 4L, NA, 3L, NA, NA, NA, 5L, 7L, NA, 
6L, NA, NA, NA, NA, 7L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
7L, NA, NA, NA, NA, NA, NA, 6L, 2L, NA, NA, NA, 5L, 4L, NA, NA, 
5L, 4L, NA, 5L, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, 
NA, NA, NA, 3L, 3L, 5L, NA, 4L, NA, NA, 3L, 3L, NA, 1L, NA, NA, 
NA, NA, NA, NA, 11L, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 5L, 
5L, NA, 5L, NA, NA, NA, 6L, NA, NA, NA, NA, 3L, NA, 2L, NA, NA, 
4L, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, 12L, 7L, 11L, 10L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 2L, 4L, 6L, 6L, 6L, 5L, 
6L, 6L, 6L, 6L, 6L, 5L, 5L, 4L, 6L, 6L, 2L, 5L, 5L, 5L, 5L, 5L, 
NA, NA, NA, 5L, 11L, NA, NA, NA, 2L, 6L, 7L, 7L, 7L, 3L, 7L, 
6L, NA, NA, 4L, NA, NA, NA, 10L, 9L, 6L, NA, 6L, NA, NA, NA, 
NA, NA, NA, 4L, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, 
1L, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 
NA, NA, 3L, NA, NA, NA, NA, 6L, 6L, 6L, 1L, 6L, NA, NA, 4L, NA, 
NA, NA, 12L, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 4L, 6L, 5L, 
5L, NA, 4L, 5L, 5L, NA, NA, 6L, NA, 4L, 4L, 3L, 4L, 7L, 7L, NA, 
4L, NA, NA, 2L, 1L, 7L, NA, NA, 10L, NA, NA, NA, NA, NA, NA, 
NA, NA, 5L, 7L, 5L, 6L, 5L, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 11L, NA, NA, 10L, NA, 4L, NA, NA, 5L, 
1L, NA, NA, 6L, NA, NA, NA, NA, 8L, NA, NA, NA, NA, NA, NA, 5L, 
1L, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, 1L, NA, 
NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 3L, 1L, 10L, 5L, 6L, NA, NA, NA, NA, NA, 5L, NA, NA, 
6L, NA, 5L, NA, 5L, 7L, NA, NA, NA, NA, NA, 5L, 6L, NA, 5L, 4L, 
8L, NA, 1L, 3L, NA, NA, 1L, NA), ceftazidime = c(NA, NA, NA, 
NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, 5L, 5L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 5L, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 3L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, 7L, NA, NA, NA, 6L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, 
NA, NA, NA, 5L, NA, NA, NA, 13L, NA, NA, NA, NA, NA, NA, NA, 
2L, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 7L, 6L, NA, NA, NA, NA, 1L, NA, NA, 
NA, NA, NA, NA, NA, 5L, 3L, NA, 3L, 3L, NA, NA, NA, NA, NA, NA, 
NA, 5L, 5L, NA, 6L, NA, NA, NA, 5L, NA, NA, 7L, NA, NA, NA, 3L, 
5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 5L, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 4L, 
NA, NA, NA, 4L, NA, NA, NA, NA, NA, 5L, NA, NA, 6L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, 
NA, NA, NA, 6L, NA, NA, NA, NA, 5L, 4L, NA, NA, 5L, 4L, NA, 5L, 
NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 5L, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
11L, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 5L, NA, NA, 5L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 4L, NA, 4L, 6L, 6L, 6L, 5L, 6L, 6L, 6L, 6L, 6L, 
5L, 5L, 4L, 6L, 6L, NA, 5L, 5L, 5L, 5L, 5L, NA, NA, NA, 5L, 11L, 
NA, NA, NA, NA, 6L, 7L, 7L, 7L, 3L, 7L, 6L, 5L, NA, 4L, NA, NA, 
NA, NA, NA, 6L, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 
6L, 6L, 6L, NA, 6L, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 4L, 4L, 6L, 5L, 5L, NA, 4L, 5L, 5L, NA, NA, 6L, 
NA, 4L, NA, NA, 4L, 7L, 7L, NA, 4L, NA, NA, NA, NA, 7L, NA, NA, 
10L, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 5L, 6L, 5L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 4L, NA, NA, 5L, NA, NA, NA, 6L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 6L, NA, NA, NA, 
NA, NA, 5L, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
5L, 6L, NA, 5L, 4L, NA, NA, NA, NA, NA, NA, NA, NA), chloram = c(NA, 
4L, 4L, 4L, NA, 6L, NA, 2L, NA, 2L, NA, NA, NA, NA, NA, NA, NA, 
1L, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 1L, NA, NA, NA, NA, 7L, NA, NA, NA, NA, 4L, NA, 6L, 
NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, 7L, NA, NA, 
NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, 8L, 6L, NA, NA, 7L, 
7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 1L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, 5L, 6L, 7L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 4L, 3L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
8L, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 
NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, 7L, NA, NA, NA, 
4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 8L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, 5L, 2L, 
NA, NA, NA, 7L, NA, NA, NA, NA, NA, 4L, NA, NA, 6L, 7L, NA, NA, 
NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, 11L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, 9L, 
4L, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 3L, 7L, 6L, 5L, 1L, 
NA, NA, NA, 5L, 10L, 9L, 6L, 3L, 6L, 4L, 3L, NA, NA, NA, NA, 
NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 4L, NA, NA, NA, NA, NA, 4L, NA, NA, 6L, NA, 7L, NA, NA, 
NA, 7L, 3L, 6L, 10L, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 5L, 10L, 5L, NA, NA, NA, NA, NA, 7L, NA, 6L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, 3L, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 10L, NA, NA, NA, NA, NA, 1L, 
NA, NA, 1L, NA, 5L, 5L, 5L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, 3L, NA, NA, 1L, NA, NA, NA, 8L, 6L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 8L, 2L, NA, NA, 7L, 
NA, NA, NA), doxy = c(NA, NA, 4L, 4L, NA, 6L, NA, NA, 1L, 2L, 
NA, NA, NA, 2L, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, 2L, NA, NA, 7L, 
NA, NA, NA, 5L, 4L, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, 
NA, NA, NA, NA, NA, 8L, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, 
13L, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, 2L, 6L, 
4L, 4L, 2L, 8L, 6L, NA, 5L, 7L, 7L, 5L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 4L, 4L, 4L, 2L, 5L, 2L, 2L, 2L, 2L, 2L, 2L, 5L, 2L, 2L, 
3L, 4L, 5L, 2L, NA, 5L, 6L, 7L, NA, NA, NA, NA, NA, NA, NA, 2L, 
NA, NA, 4L, NA, 4L, NA, NA, NA, NA, NA, NA, 3L, 4L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, 8L, 5L, 5L, 3L, 7L, NA, NA, NA, 
NA, NA, NA, NA, 5L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
11L, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 
8L, NA, NA, NA, 13L, NA, 2L, 2L, NA, NA, NA, NA, 1L, NA, 2L, 
NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 1L, 2L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, 4L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 8L, NA, NA, NA, 2L, NA, NA, 1L, NA, 3L, NA, NA, 
NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, 7L, 7L, 2L, NA, 
6L, NA, NA, NA, 6L, 6L, 6L, 7L, NA, NA, NA, 2L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, 1L, 2L, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, 3L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, NA, NA, 
2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 
1L, 1L, NA, NA, NA, NA, NA, NA, NA, 9L, NA, 2L, 2L, NA, NA, NA, 
NA, 6L, 12L, 7L, 11L, 10L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, 10L, 9L, NA, NA, 11L, 1L, NA, NA, 
NA, NA, NA, NA, NA, NA, 7L, 6L, 5L, NA, NA, 3L, 3L, 5L, 10L, 
9L, 6L, NA, 6L, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 
NA, 1L, NA, NA, NA, NA, NA, NA, 1L, 2L, NA, NA, NA, NA, NA, NA, 
2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, 2L, NA, NA, NA, NA, 12L, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 6L, NA, 7L, 2L, NA, NA, 7L, NA, 6L, 10L, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, 1L, 4L, NA, NA, NA, NA, 11L, NA, NA, 
10L, 5L, NA, NA, NA, NA, NA, 7L, NA, 6L, NA, 3L, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, 1L, 10L, NA, 2L, 2L, 5L, 3L, NA, NA, 1L, NA, NA, 5L, 
5L, 5L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 10L, NA, NA, 3L, 
NA, NA, NA, NA, NA, NA, 8L, 6L, 1L, 5L, 4L, 5L, 7L, 3L, 3L, NA, 
3L, NA, NA, NA, 2L, NA, NA, 8L, 2L, NA, 3L, 7L, NA, NA, NA), 
    enro = c(6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 
    3L, NA, NA, NA, 4L, NA, NA, NA, NA, NA, 3L, 3L, 3L, 3L, NA, 
    NA, 2L, NA, NA, NA, 3L, 1L, NA, NA, NA, NA, NA, NA, NA, NA, 
    5L, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, 3L, NA, NA, NA, 
    NA, NA, 2L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 8L, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 4L, 3L, NA, NA, 1L, NA, NA, 6L, 3L, NA, 2L, 
    NA, NA, NA, 2L, 13L, NA, NA, NA, NA, NA, 5L, NA, NA, NA, 
    NA, NA, NA, NA, 6L, NA, NA, NA, 8L, NA, 3L, 5L, 7L, NA, 5L, 
    6L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 4L, 4L, NA, 5L, NA, 
    NA, NA, NA, NA, NA, 5L, NA, NA, NA, 4L, 5L, NA, NA, NA, 6L, 
    7L, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    2L, NA, NA, 2L, NA, NA, NA, 2L, 4L, 2L, 2L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, 2L, NA, NA, NA, NA, 
    5L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, 
    NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 8L, NA, 
    NA, NA, 13L, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, 3L, NA, 5L, NA, NA, NA, NA, 2L, NA, NA, 
    NA, NA, NA, NA, NA, 3L, NA, 4L, 3L, NA, NA, 6L, NA, NA, NA, 
    NA, NA, NA, 2L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 3L, NA, 5L, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    7L, NA, NA, 6L, 4L, NA, NA, 6L, 6L, 6L, 7L, NA, NA, NA, NA, 
    NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, 
    NA, NA, NA, 2L, NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 11L, NA, NA, 1L, NA, 5L, NA, 7L, 2L, NA, NA, 5L, 
    3L, NA, NA, NA, NA, 6L, 3L, NA, NA, NA, NA, 1L, NA, NA, NA, 
    NA, NA, 9L, NA, NA, NA, 3L, NA, NA, NA, 6L, 12L, 7L, 11L, 
    10L, 6L, 5L, NA, 4L, NA, NA, NA, 5L, 5L, NA, 3L, 7L, 6L, 
    6L, 7L, 6L, 7L, 7L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, 10L, 9L, 4L, NA, 11L, NA, 3L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, 
    9L, NA, NA, NA, NA, NA, NA, 3L, 2L, NA, NA, NA, NA, NA, 2L, 
    NA, 3L, 2L, NA, NA, 2L, 4L, NA, NA, NA, 3L, NA, NA, 4L, 2L, 
    NA, 3L, NA, NA, 2L, NA, NA, 3L, NA, NA, NA, NA, 5L, 3L, 3L, 
    NA, 2L, 3L, NA, 3L, 2L, NA, NA, NA, NA, 3L, NA, NA, 2L, NA, 
    3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 5L, 12L, 
    5L, NA, 6L, 5L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, 
    NA, 2L, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, 6L, 
    NA, 7L, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, 
    NA, 3L, NA, 1L, NA, 11L, NA, 5L, 10L, NA, NA, 4L, NA, NA, 
    NA, 7L, NA, NA, 4L, NA, NA, NA, 8L, 3L, NA, NA, NA, 3L, NA, 
    5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    7L, 4L, 4L, 5L, 3L, NA, NA, 10L, NA, NA, NA, NA, 1L, NA, 
    NA, NA, 3L, 8L, NA, NA, NA, 4L, 5L, 7L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA), gentamicin = c(6L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 5L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, 
    NA, NA, NA, 1L, NA, NA, 1L, 3L, 1L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 1L, NA, NA, 1L, 1L, 1L, 1L, NA, NA, NA, NA, 
    NA, NA, NA, 8L, NA, NA, NA, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
    13L, NA, 1L, 1L, 1L, 1L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 8L, NA, NA, NA, NA, 7L, NA, 6L, 6L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 1L, 3L, 1L, 1L, 2L, 1L, 1L, 1L, 
    1L, 1L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, 
    1L, NA, 1L, 1L, NA, NA, NA, NA, NA, NA, 1L, 2L, NA, 1L, 2L, 
    1L, NA, NA, 2L, NA, 2L, 2L, 1L, 1L, 1L, 1L, NA, NA, NA, NA, 
    5L, 5L, NA, NA, 1L, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, 13L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, 1L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 
    NA, NA, 4L, NA, 1L, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, 1L, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 5L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, 4L, 
    NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
    1L, NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, 1L, NA, 
    NA, NA, NA, NA, NA, NA, 1L, 5L, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 2L, 1L, NA, NA, 1L, 
    NA, NA, 5L, 1L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 9L, NA, NA, NA, 
    NA, NA, NA, NA, NA, 12L, NA, NA, 10L, NA, 5L, 3L, 4L, NA, 
    NA, NA, 5L, 5L, NA, NA, 7L, 6L, 6L, 7L, 6L, 7L, 7L, 7L, 1L, 
    1L, 1L, 1L, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, 
    9L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
    NA, NA, 3L, NA, NA, NA, NA, 1L, 3L, NA, NA, NA, NA, NA, 3L, 
    1L, NA, NA, NA, NA, 3L, 3L, NA, 2L, 3L, NA, 3L, NA, NA, NA, 
    NA, NA, 3L, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 3L, 
    NA, NA, 2L, 5L, NA, NA, 5L, 3L, 6L, 5L, 7L, 1L, 1L, 1L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, 
    3L, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, 3L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, NA, 
    NA, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    3L, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 10L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, 3L, NA, NA, 10L, 
    NA, NA, NA, 2L, NA, NA, 2L, NA, NA, 8L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 2L, NA, NA), marbo = c(6L, NA, NA, NA, NA, 6L, NA, NA, 
    NA, NA, NA, 5L, 3L, NA, NA, NA, 4L, NA, NA, NA, 2L, NA, 3L, 
    3L, 3L, 3L, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 
    NA, NA, NA, 7L, 5L, NA, NA, 5L, NA, NA, 6L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 1L, 
    NA, NA, NA, NA, NA, NA, 1L, 1L, NA, NA, NA, 8L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 4L, 3L, NA, NA, NA, NA, NA, 
    6L, 3L, NA, NA, NA, NA, 3L, 2L, 13L, NA, NA, NA, NA, NA, 
    5L, NA, NA, NA, NA, 2L, 2L, NA, 6L, 4L, NA, NA, 8L, 6L, 3L, 
    5L, 7L, 7L, 5L, 6L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 4L, 
    4L, NA, 5L, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, 4L, 5L, 
    NA, NA, NA, 6L, 7L, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, 
    4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, 4L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 8L, 5L, 5L, NA, 7L, NA, NA, 2L, 
    NA, NA, NA, NA, 5L, 6L, NA, NA, NA, NA, NA, NA, 2L, NA, NA, 
    NA, 11L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 8L, 5L, NA, NA, 13L, NA, NA, NA, NA, NA, NA, 2L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 
    NA, 2L, NA, NA, NA, NA, NA, 2L, NA, 3L, NA, 4L, 3L, NA, NA, 
    NA, NA, NA, NA, NA, NA, 2L, 2L, 2L, 8L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, 1L, NA, NA, 5L, 4L, NA, NA, NA, NA, NA, 
    NA, NA, NA, 7L, 7L, NA, NA, 6L, NA, NA, NA, 6L, NA, 6L, 7L, 
    NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 
    NA, 5L, NA, NA, NA, NA, NA, 2L, NA, NA, 3L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 11L, NA, NA, NA, NA, 5L, NA, 7L, 
    2L, NA, NA, 5L, 3L, NA, NA, 2L, NA, 6L, 3L, NA, NA, NA, NA, 
    NA, NA, NA, 1L, NA, NA, 9L, NA, 2L, NA, NA, NA, NA, NA, 6L, 
    12L, 7L, 11L, 10L, 6L, 5L, NA, 4L, NA, NA, NA, 5L, 5L, NA, 
    3L, 7L, 6L, 6L, 7L, 6L, 7L, 7L, 7L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 10L, NA, 4L, NA, 11L, NA, 
    3L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 10L, 9L, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, 
    NA, NA, 2L, NA, NA, NA, NA, 3L, NA, 4L, NA, NA, NA, NA, NA, 
    NA, 4L, 2L, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, 
    5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, 
    NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 5L, 
    5L, 12L, 5L, NA, 6L, 5L, 7L, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 4L, NA, 2L, NA, NA, NA, NA, NA, NA, 
    6L, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 6L, NA, 7L, NA, NA, NA, NA, 3L, NA, 3L, NA, NA, NA, 
    NA, NA, NA, 4L, 3L, NA, NA, NA, 11L, NA, 5L, 10L, NA, NA, 
    NA, NA, NA, NA, 7L, 1L, NA, 4L, NA, NA, NA, 8L, 3L, 2L, NA, 
    NA, 3L, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 10L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, 7L, 4L, 4L, 5L, NA, NA, NA, 10L, NA, NA, NA, 
    NA, NA, NA, NA, NA, 3L, 8L, NA, NA, 5L, 4L, 5L, 7L, NA, NA, 
    NA, NA, 3L, NA, NA, NA, NA, NA, 8L, NA, NA, NA, 7L, NA, NA, 
    NA), orbi = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 3L, NA, NA, NA, 4L, NA, NA, NA, 2L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 5L, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, 3L, NA, NA, 
    NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 8L, NA, NA, 6L, NA, NA, NA, 
    NA, NA, NA, NA, NA, 4L, 3L, 1L, NA, NA, NA, NA, 6L, NA, NA, 
    2L, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    6L, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, 
    7L, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, 4L, 3L, NA, NA, 
    NA, NA, NA, NA, NA, 3L, NA, NA, 4L, NA, NA, NA, NA, NA, NA, 
    NA, NA, 1L, 8L, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, 
    5L, 6L, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, 11L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 8L, 5L, 
    NA, 3L, 13L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 1L, NA, NA, NA, 3L, NA, NA, 1L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, 2L, NA, 3L, 7L, 4L, 3L, NA, 4L, 6L, 5L, NA, NA, 
    NA, NA, 2L, NA, NA, 8L, NA, 1L, NA, NA, NA, 4L, NA, NA, NA, 
    NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 1L, NA, 7L, 
    7L, NA, NA, 6L, NA, 1L, NA, 6L, 6L, NA, 7L, NA, 2L, NA, NA, 
    NA, 2L, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, 
    NA, NA, NA, NA, 5L, 1L, NA, NA, NA, NA, 3L, NA, 5L, NA, 1L, 
    NA, NA, NA, NA, NA, 2L, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 11L, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, 5L, 
    3L, NA, NA, 2L, 2L, 6L, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 9L, NA, NA, NA, 3L, NA, NA, NA, 6L, 12L, 7L, 11L, 
    10L, 6L, NA, NA, 4L, NA, NA, NA, NA, NA, 1L, 3L, 7L, 6L, 
    6L, 7L, 6L, 7L, 7L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, 3L, NA, NA, NA, 
    NA, NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, 10L, 9L, 
    NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 
    3L, NA, NA, 3L, NA, 4L, NA, NA, NA, 3L, NA, NA, 4L, NA, NA, 
    3L, NA, NA, NA, NA, 1L, 3L, NA, NA, NA, NA, 5L, 3L, 3L, NA, 
    NA, 3L, NA, 3L, NA, 3L, 1L, NA, NA, NA, NA, NA, NA, NA, 3L, 
    NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, 5L, 5L, 12L, NA, 
    NA, NA, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 7L, NA, 
    NA, NA, 7L, NA, NA, NA, NA, NA, 3L, NA, 3L, 1L, NA, NA, NA, 
    NA, NA, NA, NA, 3L, 3L, NA, 3L, NA, NA, NA, NA, 1L, NA, NA, 
    3L, NA, NA, NA, 11L, NA, 5L, 10L, NA, NA, 4L, NA, NA, NA, 
    NA, NA, NA, 4L, NA, NA, NA, 8L, NA, NA, NA, NA, NA, NA, 5L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, NA, 
    NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, 7L, 
    4L, 4L, 5L, 3L, NA, NA, 10L, NA, NA, NA, 2L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, 
    NA, NA, NA, NA, 8L, NA, NA, NA, 7L, NA, NA, NA), prado = c(NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, 
    2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    13L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 11L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 13L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 9L, NA, NA, 
    NA, NA, NA, 1L, 1L, NA, 12L, NA, 11L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, 12L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, 1L, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 8L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA), tetracycline = c(6L, NA, NA, 4L, NA, 6L, NA, NA, 
    NA, NA, NA, 5L, NA, 2L, NA, NA, NA, NA, 2L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, NA, 
    2L, NA, NA, 7L, NA, NA, NA, 5L, 4L, NA, 6L, NA, NA, 1L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, 1L, NA, NA, 2L, NA, 
    NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 8L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, NA, NA, 1L, 
    6L, NA, 1L, NA, NA, NA, 3L, NA, 13L, 1L, NA, NA, NA, NA, 
    5L, NA, NA, 2L, NA, NA, NA, 2L, 6L, 4L, 4L, 2L, 8L, 6L, 3L, 
    5L, 7L, 7L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, 4L, 4L, 
    4L, 2L, 5L, 2L, 2L, 2L, 2L, 2L, 2L, 5L, 2L, 2L, 3L, 4L, 5L, 
    2L, NA, 5L, 6L, 7L, NA, NA, 1L, NA, NA, NA, NA, 2L, NA, NA, 
    NA, NA, 4L, NA, NA, 4L, NA, NA, NA, 3L, 4L, NA, 4L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 8L, 5L, 5L, 3L, 7L, NA, NA, NA, 
    NA, NA, NA, NA, 5L, 6L, NA, 1L, 1L, NA, 1L, NA, NA, NA, NA, 
    NA, 11L, NA, NA, 3L, NA, 1L, NA, NA, NA, NA, NA, NA, NA, 
    NA, 4L, 8L, NA, NA, NA, 13L, NA, 2L, 2L, NA, NA, NA, NA, 
    NA, 1L, 2L, NA, 1L, NA, NA, NA, NA, NA, NA, 5L, NA, NA, 2L, 
    1L, NA, 2L, NA, NA, NA, NA, NA, NA, NA, 7L, NA, NA, NA, NA, 
    6L, NA, NA, NA, 1L, NA, NA, NA, NA, 8L, 6L, NA, NA, 2L, NA, 
    NA, NA, NA, 3L, NA, NA, NA, 1L, 5L, 4L, NA, 7L, NA, NA, NA, 
    NA, NA, NA, 7L, 7L, 2L, 1L, 6L, 4L, NA, 4L, 6L, 6L, 6L, 7L, 
    NA, NA, 1L, 2L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 
    NA, NA, 4L, NA, NA, 2L, 2L, NA, 5L, NA, NA, 2L, 1L, 1L, NA, 
    NA, NA, 1L, NA, 3L, 3L, NA, NA, NA, NA, 3L, NA, NA, NA, NA, 
    NA, 2L, 2L, NA, NA, NA, 11L, 1L, NA, NA, 2L, 5L, NA, 7L, 
    NA, NA, NA, NA, NA, NA, NA, NA, 2L, 6L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 9L, 1L, NA, 2L, NA, NA, NA, NA, 6L, 
    12L, 7L, 11L, 10L, 6L, 5L, 3L, NA, NA, NA, NA, 5L, 5L, NA, 
    NA, 7L, 6L, 6L, 7L, 6L, 7L, 7L, 7L, NA, NA, NA, NA, 1L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 10L, 9L, NA, NA, 11L, NA, 
    NA, 2L, NA, NA, NA, NA, NA, NA, 7L, 6L, 5L, NA, NA, 3L, 3L, 
    5L, 10L, 9L, 6L, 3L, 6L, 4L, 3L, NA, NA, NA, NA, NA, NA, 
    NA, 1L, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1L, NA, 2L, 
    5L, NA, NA, 1L, NA, NA, 2L, NA, NA, NA, NA, 1L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, 5L, 
    5L, 12L, 5L, 3L, 6L, 5L, 7L, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    6L, NA, 7L, 2L, NA, NA, 7L, 3L, 6L, 10L, NA, NA, NA, NA, 
    NA, NA, NA, 6L, NA, 7L, NA, NA, NA, NA, 3L, NA, 3L, 1L, NA, 
    NA, 1L, NA, NA, 4L, NA, 1L, NA, 1L, 11L, 1L, NA, 10L, 5L, 
    NA, 4L, NA, NA, NA, 7L, NA, 6L, 4L, 3L, NA, NA, NA, NA, 2L, 
    NA, 1L, NA, NA, NA, NA, NA, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, NA, 10L, NA, 2L, 2L, 5L, 3L, NA, NA, NA, NA, NA, 5L, 
    5L, 5L, 5L, NA, 7L, 4L, 4L, 5L, NA, NA, NA, 10L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, 8L, 6L, NA, 5L, 4L, 5L, 7L, 3L, 
    3L, 1L, 3L, NA, NA, NA, 2L, NA, NA, 8L, NA, NA, 3L, 7L, NA, 
    NA, 1L), trimeth_sulfameth = c(6L, 4L, 4L, 4L, NA, 6L, 1L, 
    2L, NA, NA, NA, 5L, NA, NA, 1L, NA, 4L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 7L, 5L, NA, NA, 5L, 4L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 8L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    5L, NA, NA, NA, NA, 2L, 2L, NA, 6L, 4L, 4L, NA, 8L, 6L, NA, 
    5L, 7L, 7L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, 
    NA, NA, 5L, 6L, 7L, NA, NA, NA, NA, 4L, NA, NA, NA, 1L, NA, 
    NA, NA, 4L, NA, NA, 4L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, 5L, 5L, NA, NA, NA, NA, NA, 
    7L, NA, NA, NA, NA, 6L, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, 8L, 5L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 5L, 4L, NA, 7L, NA, NA, 5L, NA, NA, 
    NA, NA, NA, NA, NA, NA, 4L, NA, NA, NA, 6L, 6L, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    4L, NA, NA, NA, 2L, NA, 5L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, 
    2L, NA, NA, NA, 11L, NA, NA, NA, NA, 5L, NA, 7L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, 9L, NA, NA, NA, 3L, NA, NA, NA, NA, NA, NA, 
    NA, 10L, 6L, 5L, 3L, NA, 1L, 1L, 1L, 5L, 5L, NA, NA, 7L, 
    6L, 6L, 7L, 6L, 7L, 7L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, 10L, 9L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 3L, 3L, 5L, 10L, 
    9L, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, 
    NA, NA, 2L, NA, NA, 2L, NA, 1L, NA, NA, NA, NA, 1L, 4L, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5L, NA, NA, 
    NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 
    NA, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 12L, 
    5L, 3L, 6L, 5L, 7L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 6L, NA, 7L, 
    NA, NA, NA, NA, 3L, 6L, 10L, 1L, 1L, NA, NA, NA, NA, NA, 
    6L, NA, 7L, NA, NA, NA, NA, NA, NA, NA, NA, 1L, 2L, NA, NA, 
    NA, 4L, NA, NA, NA, NA, NA, NA, NA, 10L, 5L, NA, NA, NA, 
    NA, NA, 7L, NA, NA, NA, 3L, 1L, NA, NA, NA, NA, 1L, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 10L, 
    NA, NA, NA, 5L, 3L, NA, NA, NA, NA, NA, 5L, 5L, 5L, 5L, NA, 
    7L, NA, NA, 5L, NA, NA, NA, NA, NA, NA, 3L, NA, NA, NA, NA, 
    NA, 3L, 8L, NA, NA, 5L, NA, NA, 7L, NA, NA, NA, NA, NA, NA, 
    NA, NA, NA, NA, NA, NA, NA, NA, NA, 2L, NA, NA)), class = "data.frame", row.names = c(NA, 
-733L))
